{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.application.name }}-external-secrets"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRefName | default "vault-backend-customer" }}
    kind: {{ .Values.externalSecrets.secretStoreRefKind | default "SecretStore" }}
  target:
    name: "{{ .Values.application.name }}-external-secrets"
    creationPolicy: 'Owner'
  data:
{{- range .Values.externalSecrets.secretData }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ .remoteRefKey }}
      property: {{ .property }}
{{- end }}
{{- end }}
