---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.application.name }}-svc"
  labels:
    application: {{ .Values.application.name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    application: {{ .Values.application.name }}

